export default [
  {
    name: 'The Willows',
    id: 'jk1',
    img: '',
    address: '3517 w. Gray St. Utica',
    numberRoom: 3,
    numberBathroom: 2,
    superficie: '230ft',
    costMonth: '440/m',
    evaluation: 4.7,
  },
  {
    name: 'Orchard House',
    id: 'jk2',
    img: '',
    address: '3517 w. Gray St. Utica',
    numberRoom: 3,
    numberBathroom: 2,
    superficie: '230ft',
    costMonth: '440/m',
    evaluation: 4.7,
  },
  {
    name: 'Orchard House',
    id: 'jk3',
    img: '',
    address: '3517 w. Gray St. Utica',
    numberRoom: 3,
    numberBathroom: 2,
    superficie: '230ft',
    costMonth: '440/m',
    evaluation: 4.7,
  },
  {
    name: 'Corner House',
    id: 'jk4',
    img: '',
    address: '3517 w. Gray St. Utica',
    numberRoom: 3,
    numberBathroom: 2,
    superficie: '230ft',
    costMonth: '440/m',
    evaluation: 4.7,
  },
];
